-- FPCourse.lean — library root; imports all 14 weekly modules (Weeks 0-12, 14)

import FPCourse.T01_ExpressionsFunctionsRecursion.Week00_AlgebraicTypes
import FPCourse.T01_ExpressionsFunctionsRecursion.Week01_ExpressionsTypesValues
import FPCourse.T01_ExpressionsFunctionsRecursion.Week02_FunctionsSpecifications
import FPCourse.T01_ExpressionsFunctionsRecursion.Week03_RecursionTermination

import FPCourse.T02_InductiveTypes.Week04_AlgebraicDatatypes
import FPCourse.T02_InductiveTypes.Week05_Lists
import FPCourse.T02_InductiveTypes.Week06_Trees
import FPCourse.T02_InductiveTypes.Week07_PolymorphismDecidability

import FPCourse.T03_HigherOrderAndSpecification.Week08_HigherOrderFunctions
import FPCourse.T03_HigherOrderAndSpecification.Week09_Specifications

import FPCourse.T04_SetsAndRelations.Week10_SetsRelations

import FPCourse.T05_AbstractTypesAndTypeClasses.Week11_AbstractTypes
import FPCourse.T05_AbstractTypesAndTypeClasses.Week12_TypeClassesDecidable

import FPCourse.T06_StreamsAndCurryHoward.Week14_CurryHoward
