-- FPCourse.lean — library root; imports all 15 weekly modules (Weeks 0-14)

import FPCourse.ExpressionsFunctionsRecursion.Week00_AlgebraicTypes
import FPCourse.ExpressionsFunctionsRecursion.Week01_ExpressionsTypesValues
import FPCourse.ExpressionsFunctionsRecursion.Week02_FunctionsSpecifications
import FPCourse.ExpressionsFunctionsRecursion.Week03_RecursionTermination

import FPCourse.InductiveStructures.Week04_AlgebraicDatatypes
import FPCourse.InductiveStructures.Week05_Lists
import FPCourse.InductiveStructures.Week06_Trees
import FPCourse.InductiveStructures.Week07_PolymorphismDecidability

import FPCourse.HigherOrderAndSpecification.Week08_HigherOrderFunctions
import FPCourse.HigherOrderAndSpecification.Week09_Specifications

import FPCourse.SetsAndRelations.Week10_SetsRelations

import FPCourse.AbstractTypesAndTypeClasses.Week11_AbstractTypes
import FPCourse.AbstractTypesAndTypeClasses.Week12_TypeClassesDecidable

import FPCourse.StreamsAndCurryHoward.Week13_Streams
import FPCourse.StreamsAndCurryHoward.Week14_CurryHoward
